version: "3.7"
services:
  redis:
    image: redis:7.0.5
    ports:
      - $REDIS_PORT:$REDIS_PORT
    command: redis-server --requirepass $$REDIS_PASSWORD
  api:
    build:
      context: .
      dockerfile: .docker/ci/Dockerfile
    command: npm run start:prod
    env_file: .env
    restart: always
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - redis
  microservice:
    build:
      context: .
      dockerfile: .docker/ci/Dockerfile
    command: npm run start:microservice:prod
    env_file: .env
    ports:
      - $MICROSERVICE_PORT:$MICROSERVICE_PORT
    depends_on:
      - redis
