version: "3.7"
services:
  redis:
    image: redis:7.0.5-alpine
    ports:
      - $REDIS_PORT:$REDIS_PORT
    command: redis-server --requirepass $$REDIS_PASSWORD
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
      args:
        PORT: ${API_PORT}
        HOST: ${API_HOST}
    env_file: .env
    depends_on:
      - api
    ports:
      - $API_PORT:$API_PORT
  api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    command: npm run start:prod
    expose:
      - $API_PORT
  microservice:
    build:
      context: .
      dockerfile: .docker/microservice/Dockerfile
    command: npm run start:microservice:prod
    env_file: .env
    ports:
      - $MICROSERVICE_PORT:$MICROSERVICE_PORT
    depends_on:
      - redis
